default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: womenrising_development
  <% if ENV['WOMENRISING_DOCKER'] %>
  username: postgres
  password:
  host: postgres
  <% end %>

test:
  <<: *default
  database: womenrising_test
  <% if ENV['WOMENRISING_DOCKER'] %>
  username: postgres
  password:
  host: postgres
  <% end %>
